### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by anaderi** [yandex/rep#24]
after `python setup.py install` I run `cd tests ; nosetests . `
it runs for long time and ends up with errors:

```
..Info in <TCanvas::Print>: png file /tmp/tmpBg1dar.png has been created
Error in <TFile::TFile>: file toy_datasets/toyMC_bck_mass.root does not exist
E..E.
======================================================================
ERROR: tests.z_test_notebook.test_notebooks_in_folder('/root/rep/howto/00-intro-ROOT.ipynb',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/root/rep/rep/test/test_notebooks.py", line 43, in check_single_notebook
    raise RuntimeError(description)
RuntimeError: Cell failed: 'T.Draw("min_DOCA")
c1'

 Traceback:
---------------------------------------------------------------------------
ReferenceError                            Traceback (most recent call last)
<ipython-input-5-aa6c7320180d> in <module>()
----> 1 T.Draw("min_DOCA")
      2 c1

ReferenceError: attempt to access a null-pointer
```
What am I missing?

**Comment by arogozhnikov** [comment]
> Error in <TFile::TFile>: file toy_datasets/toyMC_bck_mass.root does not exist
Is it the reason?

**Comment by anaderi** [comment]
if we cannot have toyMC_bck_mass.root it, maybe we can use a simpler example of root-file for testing?

**Comment by arogozhnikov** [comment]
In develop branch current version of ROOT notebook doesn't require any files. Are you testing develop?
