### ISSUE TITLE
develop branch doesn't fly under jupyterhub/everware

### ISSUE THREAD

**Issue by anaderi** [yandex/rep#83]
as I start develop version under jupyterhub, it reports in log and fails:

```
Starting under Jupyterhub
fatal: destination path '/notebooks' already exists and is not an empty directory.
Traceback (most recent call last):
  File "/root/miniconda/envs/jupyterhub_py3/bin/jupyterhub-singleuser", line 21, in <module>
    import notebook
ImportError: No module named 'notebook'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda/envs/jupyterhub_py3/bin/jupyterhub-singleuser", line 23, in <module>
    raise ImportError("JupyterHub single-user server requires notebook >= 4.0")
ImportError: JupyterHub single-user server requires notebook >= 4.0
```

**Comment by arogozhnikov** [comment]
fixed in https://github.com/yandex/rep/commit/23674d450a02e5e5adea0aeac07c627717e83120
